<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
?>
<?= '<?xml version="1.0" encoding="UTF-8" ?>'; ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:media="http://search.yahoo.com/mrss/" <?=
	$this->rss_base === '' ? '' : ' xml:base="' . $this->rss_base . '"' ?>>
	<channel>
		<title><?= $this->rss_title ?></title>
		<link><?= $this->html_url ?></link>
		<description><?= $this->description ?: _t('index.feed.rss_of', $this->rss_title) ?></description>
		<pubDate><?= date('D, d M Y H:i:s O') ?></pubDate>
		<lastBuildDate><?= gmdate('D, d M Y H:i:s') ?> GMT</lastBuildDate>
		<atom:link href="<?= $this->rss_url ?>" rel="self" type="application/rss+xml" />
		<?php if ($this->image_url !== ''): ?>
		<image>
			<url><?= $this->image_url ?></url>
			<title><?= $this->rss_title ?></title>
			<link><?= $this->html_url ?></link>
		</image>
		<?php endif; ?>
<?php
foreach ($this->entries as $item) {
	if (!$this->internal_rendering) {
		/** @var FreshRSS_Entry|null $item */
		$item = Minz_ExtensionManager::callHook(Minz_HookType::EntryBeforeDisplay, $item);
		if ($item === null) {
			continue;
		}
	}
?>
		<item>
			<title><?= $item->title() ?></title>
			<link><?= $item->link() ?></link>
			<?php
				$authors = $item->authors();
				if (is_array($authors)) {
					foreach ($authors as $author) {
						echo "\t\t\t", '<dc:creator>', $author, '</dc:creator>', "\n";
					}
				}

				if ($this->publishLabelsInsteadOfTags) {
					$categories = $this->entryIdsTagNames['e_' . $item->id()] ?? [];
					if (is_array($categories)) {
						foreach ($categories as $category) {
							echo "\t\t\t", '<category>', $category, '</category>', "\n";
						}
					}
				} else {
					$categories = $item->tags();
					if (is_array($categories)) {
						foreach ($categories as $category) {
							echo "\t\t\t", '<category>', $category, '</category>', "\n";
						}
					}
				}

				$enclosures = iterator_to_array($item->enclosures(false), preserve_keys: false);	// TODO: Optimise: avoid iterator_to_array if possible
				$thumbnail = $item->thumbnail(false);
				if (!empty($thumbnail['url'])) {
					// https://www.rssboard.org/media-rss#media-thumbnails
					echo "\t\t\t", '<media:thumbnail url="' . htmlspecialchars($thumbnail['url'], ENT_QUOTES, 'UTF-8')
						. (empty($thumbnail['width']) ? '' : '" width="' . htmlspecialchars((string)$thumbnail['width'], ENT_QUOTES, 'UTF-8'))
						. (empty($thumbnail['height']) ? '' : '" height="' . htmlspecialchars((string)$thumbnail['height'], ENT_QUOTES, 'UTF-8'))
						. (empty($thumbnail['time']) ? '' : '" time="' . htmlspecialchars($thumbnail['time'], ENT_QUOTES, 'UTF-8'))
						. '" />', "\n";
					// Mostly for MailChimp + Feedbro which do not support <media:thumbnail> https://mailchimp.com/help/rss-merge-tags/
					$thumbnail['medium'] ??= 'image';
					array_unshift($enclosures, $thumbnail);
				}

				$urls = [];
				foreach ($enclosures as $enclosure) {
					if (empty($enclosure['url']) || isset($urls[$enclosure['url']])) {
						continue;
					}
					$urls[$enclosure['url']] = true;

					$credits = $enclosure['credit'] ?? [];
					if (!is_array($credits)) {	// For entries < FreshRSS 1.24
						$credits = [$credits];
					}
					$mediaCredits = '';
					foreach ($credits as $credit) {
						$mediaCredits = '<media:credit>' . htmlspecialchars($credit, ENT_QUOTES, 'UTF-8') . '</media:credit>';
					}

					// https://www.rssboard.org/media-rss
					echo "\t\t\t", '<media:content url="' . htmlspecialchars($enclosure['url'], ENT_QUOTES, 'UTF-8')
						. (empty($enclosure['medium']) ? '' : '" medium="' . htmlspecialchars($enclosure['medium'], ENT_QUOTES, 'UTF-8'))
						. (empty($enclosure['type']) ? '' : '" type="' . htmlspecialchars($enclosure['type'], ENT_QUOTES, 'UTF-8'))
						. (empty($enclosure['length']) ? '' : '" length="' . htmlspecialchars((string)$enclosure['length'], ENT_QUOTES, 'UTF-8'))
						. (empty($enclosure['height']) ? '' : '" height="' . htmlspecialchars((string)$enclosure['height'], ENT_QUOTES, 'UTF-8'))
						. (empty($enclosure['width']) ? '' : '" width="' . htmlspecialchars((string)$enclosure['width'], ENT_QUOTES, 'UTF-8'))
						. '">'
						. (empty($enclosure['title']) ? '' : '<media:title type="html">' . htmlspecialchars($enclosure['title'], ENT_QUOTES, 'UTF-8') . '</media:title>')
						. $mediaCredits
						. '</media:content>', "\n";
				}
			?>
			<description><![CDATA[<?php
	echo $item->content(false);
?>]]></description>
			<pubDate><?= date('D, d M Y H:i:s O', $item->date(true)) ?></pubDate>
			<guid isPermaLink="false"><?= $item->id() > 0 ? $item->id() : $item->guid() ?></guid>
		</item>
<?php } ?>

	</channel>
</rss>
